### ISSUE TITLE
Bonelord in the Jakundaf library

### ISSUE THREAD

**Issue by VitorLuizC** [s2ward/469#17]
It would be nice to include the Facebook post of Bonelord in the Jakundaf library. Cony Island found it and shared on Tibia Secrets discord channel, and it probably help in the future translation.

Link to Cony Island message:
https://discord.com/channels/870695446073458698/871057787411636285/1074816457856254062

The image:
![image](https://user-images.githubusercontent.com/9027363/219766489-1b618002-22df-4ae4-b256-9b29ea98b681.png)

**Comment by zephirusgit** [comment]
hola bro! XD  andaba muy aburrido por irme a dormir, y justo se me ocurrió buscar en mi tablet los libros de los beholders, no los encuentro aun en el pc (y nose en que char de tibia tengo los libros) asi que me puse a googlear y llegue hasta acá. ya es muy tarde aquí 6:30am pero he tenido una revelación, asi que voy a ver si los descargo de alguna wiki, para ver si tiene sentido lo que se me ocurrió.  cuando pueda analizar bien mi teoria si puedo te cuento.  saludos

**Comment by s2ward** [comment]
Hi @VitorLuizC! 
Thanks for pointing this to my attention, funnily enough I am Cony Island on discord ;) 

I have a writeup I am working on which will hopefully be released in March, and after it is done and published, I will update the repository with new findings. 

Stay tuned!

**Comment by VitorLuizC** [comment]
Since you're Cony Island and is already working on this, I can safely close the issue.
